return {
    FLY_SWORD = {
        weaponId = 'FLY_SWORD',
        weaponAttach = true,
        weaponDamage = 1,
        weaponOnceAttackCooldown = 2,
        weaponOnceAttackSingleTimes = 2,
        weaponOnceAttackDuration = 0.2,
        weaponBulletSpeed = 10,
        weaponAttackRange = -1,
    },
    BLAST_GUN = {
        weaponId = 'BLAST_GUN',
        weaponAttach = true,
        weaponDamage = 1,
        weaponOnceAttackCooldown = 1.5,
        weaponOnceAttackSingleTimes = 1,
        weaponOnceAttackDuration = 0.1,
        weaponBulletSpeed = 5,
        weaponAttackRange = -1,
    },
    TOXIC_ZONE = {
        weaponId = 'TOXIC_ZONE',
        weaponAttach = false,
        weaponDamage = 1,
        weaponOnceAttackCooldown = 1,
        weaponOnceAttackSingleTimes = 1,
        weaponOnceAttackDuration = 0.1,
        weaponBulletSpeed = 0,
        weaponAttackRange = 300,
    },
    ONION_SWORD = {
        weaponId = 'ONION_SWORD',
        weaponAttach = true,
        weaponDamage = 1,
        weaponOnceAttackCooldown = 2,
        weaponOnceAttackSingleTimes = 1,
        weaponOnceAttackDuration = 0.2,
        weaponBulletSpeed = 10,
        weaponAttackRange = -1,
    },
    SHOTGUN = {
        weaponId = 'SHOTGUN',
        weaponAttach = true,
        weaponDamage = 1,
        weaponOnceAttackCooldown = 1.2,
        weaponOnceAttackSingleTimes = 1,
        weaponOnceAttackDuration = 0.1,
        weaponBulletSpeed = 20,
        weaponAttackRange = -1,
    },
    THUNDER_FIST = {
        weaponId = 'THUNDER_FIST',
        weaponAttach = true,
        weaponDamage = 1,
        weaponOnceAttackCooldown = 2,
        weaponOnceAttackSingleTimes = 1,
        weaponOnceAttackDuration = 0.1,
        weaponBulletSpeed = 10,
        weaponAttackRange = -1,
    },
}
